name: Prettier Check

on:
  # Run the workflow on pushes and pull requests
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  prettier:
    name: Run Prettier Check
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Run Prettier check
      - name: Run Prettier Check
        run: npx prettier --check .
